<?php

namespace Database\Seeders;

use App\Models\Quiz;
use App\Models\QuizQuestion;
use Illuminate\Database\Seeder;

/**
 * 將 5 個測驗的題庫各擴充至 50 題，所有題目與選項獨一無二。
 */
class ExpandQuestionPoolsSeeder extends Seeder
{
    public function run(): void
    {
        $this->expandCharisma();
        $this->expandBehavior();
        $this->expandFirstImpression();
        $this->expandLifeDirection();
        $this->expandEmotionalStress();
        $this->command->info('✅ 5 個測驗題庫已擴充至 50 題');
    }

    private function addQuestions(string $slug, array $questions): void
    {
        $quiz = Quiz::where('slug', $slug)->firstOrFail();
        $maxOrder = QuizQuestion::where('quiz_id', $quiz->id)->max('sort_order') ?? 0;
        $needed = 50 - QuizQuestion::where('quiz_id', $quiz->id)->count();
        $toAdd = array_slice($questions, 0, $needed);
        foreach ($toAdd as $i => $q) {
            QuizQuestion::create([
                'quiz_id'     => $quiz->id,
                'body'        => $q['body'],
                'type'        => 'single_choice',
                'options'     => $q['options'],
                'sort_order'  => $maxOrder + $i + 1,
                'is_required' => true,
            ]);
        }
        $final = QuizQuestion::where('quiz_id', $quiz->id)->count();
        $this->command->info("{$slug}: 新增 " . count($toAdd) . " 題，共 {$final} 題");
    }

    // =========================================================================
    // 魅力吸引力 (需補到 50 題，目前 19 題，補 31 題)
    // =========================================================================
    private function expandCharisma(): void
    {
        $this->addQuestions('charisma-attraction', [
            ['body'=>'你認為「魅力」這件事，天生的成分有多少？',
             'options'=>[
                ['key'=>'a','label'=>'完全天生，改變不了太多','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'天生一半，後天練習也能提升','scores'=>['VERBAL_C'=>2,'CONFIDENT_C'=>2],'dim_scores'=>['VERBAL'=>12,'PRESENCE'=>14]],
                ['key'=>'c','label'=>'主要靠後天培養，尤其是溫暖和真誠','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'魅力是一種態度，和天生無關','scores'=>['FREE_C'=>3],'dim_scores'=>['MYSTERY_C'=>12,'PRESENCE'=>14]],
            ]],
            ['body'=>'你最享受在哪種情況下展現自己？',
             'options'=>[
                ['key'=>'a','label'=>'在一大群人面前，感覺到大家的眼光','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'在一對一深度對話中，完全投入','scores'=>['VERBAL_C'=>2,'INTELLECTUAL_C'=>2],'dim_scores'=>['VERBAL'=>14,'MYSTERY_C'=>12]],
                ['key'=>'c','label'=>'在幫助某人的過程中，感到連結','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'在沒有規則的場合，自由發揮','scores'=>['FREE_C'=>3],'dim_scores'=>['MYSTERY_C'=>14,'PRESENCE'=>12]],
            ]],
            ['body'=>'你認為讓人留下深刻印象的關鍵是？',
             'options'=>[
                ['key'=>'a','label'=>'一種難以複製的個人存在感','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'說出對方心裡想說但說不出的話','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'真正記得對方說過的細節','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>16,'TRUST_BASED'=>10]],
                ['key'=>'d','label'=>'有一種讓人永遠猜不透的深度','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'你如何讓一段對話不尷尬？',
             'options'=>[
                ['key'=>'a','label'=>'用我的能量帶動氣氛','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>16,'EMOTIONAL'=>10]],
                ['key'=>'b','label'=>'說一個笑話或有趣的觀察','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'問對方感興趣的問題，讓他說話','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>16,'TRUST_BASED'=>10]],
                ['key'=>'d','label'=>'讓沉默自然存在，不強迫填補','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>16,'PRESENCE'=>10]],
            ]],
            ['body'=>'你認為吸引力最持久的形式是什麼？',
             'options'=>[
                ['key'=>'a','label'=>'那種讓人每次見面都感到驚喜的能量','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'讓每次對話都讓人感到值得','scores'=>['VERBAL_C'=>2,'INTELLECTUAL_C'=>2],'dim_scores'=>['VERBAL'=>14,'MYSTERY_C'=>12]],
                ['key'=>'c','label'=>'讓人在脆弱時第一個想到你','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>16,'TRUST_BASED'=>10]],
                ['key'=>'d','label'=>'永遠有讓人好奇的層次','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'被陌生人問到「你是做什麼的？」你怎麼回答？',
             'options'=>[
                ['key'=>'a','label'=>'用一句讓對方意外或印象深刻的描述','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>16,'EMOTIONAL'=>10]],
                ['key'=>'b','label'=>'用故事包裝，讓職業變得有趣','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'反問對方，把焦點轉移到他身上','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>16,'TRUST_BASED'=>10]],
                ['key'=>'d','label'=>'給一個模糊的答案，讓對方好奇','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'你如何讓一個不太熟的人開始喜歡你？',
             'options'=>[
                ['key'=>'a','label'=>'展現我的自信，讓他們尊重我','scores'=>['CONFIDENT_C'=>3],'dim_scores'=>['PRESENCE'=>18,'TRUST_BASED'=>8]],
                ['key'=>'b','label'=>'用幽默和輕鬆的話題打開局面','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'記住他說過的事，下次提起','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'保持適當距離，讓他們主動靠近','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'你最有魅力的表情或狀態是？',
             'options'=>[
                ['key'=>'a','label'=>'全神貫注、眼神有力的時候','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'在講述一個精彩故事的時候','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'在傾聽別人，完全專注於他的時候','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'若有所思、安靜的時候','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'你認為什麼時候你最「不像自己」？',
             'options'=>[
                ['key'=>'a','label'=>'被迫消失在人群中，沒有存在感','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>16,'EMOTIONAL'=>10]],
                ['key'=>'b','label'=>'被要求安靜，不能表達','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>16,'PRESENCE'=>10]],
                ['key'=>'c','label'=>'在冷漠的環境裡，沒有情感連結','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>16,'TRUST_BASED'=>10]],
                ['key'=>'d','label'=>'在所有人都了解我的圈子裡','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'你在一段關係開始時，最吸引對方的是？',
             'options'=>[
                ['key'=>'a','label'=>'我整個人散發的那種能量和氣場','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'我說的話讓他們覺得被真正理解','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>16,'EMOTIONAL'=>10]],
                ['key'=>'c','label'=>'我讓他們感到被接受和珍惜','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'我有種他們一直想解開的謎','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'你覺得你的弱點是什麼？',
             'options'=>[
                ['key'=>'a','label'=>'有時太依賴外在的反應來確認自己','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>14,'EMOTIONAL'=>12]],
                ['key'=>'b','label'=>'有時說太多，沒給對方空間','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>14,'PRESENCE'=>12]],
                ['key'=>'c','label'=>'有時太在乎對方的感受，忽略自己','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>14,'TRUST_BASED'=>12]],
                ['key'=>'d','label'=>'有時太難接近，讓人感到疏遠','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>16,'PRESENCE'=>10]],
            ]],
            ['body'=>'如果你和一個完全不認識的人被困在電梯裡，你會？',
             'options'=>[
                ['key'=>'a','label'=>'讓氣氛輕鬆，用我的存在感化解尷尬','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'找個話題聊起來，讓時間過得快','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'先問他還好嗎，從對方的狀態出發','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>16,'TRUST_BASED'=>10]],
                ['key'=>'d','label'=>'安靜待著，讓對方決定要不要說話','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>16,'PRESENCE'=>10]],
            ]],
            ['body'=>'你認為讓人真正信服你的方式是？',
             'options'=>[
                ['key'=>'a','label'=>'讓他們感受到我的存在和力量','scores'=>['MAGNETIC_C'=>2,'CONFIDENT_C'=>2],'dim_scores'=>['PRESENCE'=>14,'TRUST_BASED'=>12]],
                ['key'=>'b','label'=>'用清晰有力的語言表達我的立場','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'用長期的行動讓他們知道我可靠','scores'=>['RELIABLE_C'=>3],'dim_scores'=>['TRUST_BASED'=>18,'EMOTIONAL'=>8]],
                ['key'=>'d','label'=>'展示我獨特的視角和深度','scores'=>['INTELLECTUAL_C'=>3],'dim_scores'=>['VERBAL'=>14,'MYSTERY_C'=>12]],
            ]],
            ['body'=>'當你感到最有魅力的時候，通常是？',
             'options'=>[
                ['key'=>'a','label'=>'完全沉浸在自己喜歡做的事裡','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>16,'EMOTIONAL'=>10]],
                ['key'=>'b','label'=>'剛說出一句讓人眼前一亮的話','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'剛剛幫助了某個真正需要幫助的人','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'剛做了一個出人意料的決定','scores'=>['FREE_C'=>3],'dim_scores'=>['MYSTERY_C'=>14,'PRESENCE'=>12]],
            ]],
            ['body'=>'你如何在一段關係中保持吸引力？',
             'options'=>[
                ['key'=>'a','label'=>'持續帶來新鮮感和能量','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'不斷有新的想法和話題','scores'=>['VERBAL_C'=>2,'INTELLECTUAL_C'=>2],'dim_scores'=>['VERBAL'=>14,'MYSTERY_C'=>12]],
                ['key'=>'c','label'=>'讓對方感到被看見和珍惜','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'保持一些神秘，讓對方繼續好奇','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'你認為「有趣的人」具備什麼特質？',
             'options'=>[
                ['key'=>'a','label'=>'讓人覺得和他在一起很有活力','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'有辦法把任何話題說得引人入勝','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'真心在意對方，不讓人感到孤單','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'永遠有讓你意想不到的一面','scores'=>['FREE_C'=>2,'MYSTERIOUS_C'=>2],'dim_scores'=>['MYSTERY_C'=>14,'PRESENCE'=>12]],
            ]],
            ['body'=>'你的哪個行為最讓人感到你的魅力？',
             'options'=>[
                ['key'=>'a','label'=>'進入一個房間時的那種存在感','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'在對話中說出那句話，讓全場安靜','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'在別人沮喪時，知道怎麼讓他們感覺好一點','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'做出一個沒人預料到的選擇','scores'=>['MYSTERIOUS_C'=>2,'FREE_C'=>2],'dim_scores'=>['MYSTERY_C'=>14,'PRESENCE'=>12]],
            ]],
            ['body'=>'你最希望別人在說起你時，用什麼形容詞？',
             'options'=>[
                ['key'=>'a','label'=>'充滿魅力，讓人印象深刻','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'風趣，和他說話是一種享受','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'溫暖，在他身邊感到被接受','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'有深度，和他說話讓人有收穫','scores'=>['INTELLECTUAL_C'=>3],'dim_scores'=>['VERBAL'=>14,'MYSTERY_C'=>12]],
            ]],
            ['body'=>'當你想讓某人注意到你，你會怎麼做？',
             'options'=>[
                ['key'=>'a','label'=>'調整我的存在感，讓自己更有吸引力','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'在適當時機說出一句讓他印象深刻的話','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'主動關心他，讓他感受到我的溫度','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>16,'TRUST_BASED'=>10]],
                ['key'=>'d','label'=>'保持一種若即若離，讓他來找我','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'你最怕在別人眼中變成怎樣的人？',
             'options'=>[
                ['key'=>'a','label'=>'平淡無奇，沒有任何記憶點','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'無聊乏味，說話沒有重點','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'冷漠疏遠，讓人感到不被在乎','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'太好猜，毫無驚喜感','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'在一個你想給人好印象的場合，你最依賴的是？',
             'options'=>[
                ['key'=>'a','label'=>'我的整體氣場和存在方式','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'我準備好的話題和表達方式','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'我真實的關心和溫度','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'我自然流露的獨特和不做作','scores'=>['FREE_C'=>3],'dim_scores'=>['MYSTERY_C'=>14,'PRESENCE'=>12]],
            ]],
            ['body'=>'你認為你的哪種行為會消耗你的魅力？',
             'options'=>[
                ['key'=>'a','label'=>'過度在意別人對我的看法','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>14,'EMOTIONAL'=>12]],
                ['key'=>'b','label'=>'說太多，不給對方空間','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>14,'PRESENCE'=>12]],
                ['key'=>'c','label'=>'太強調自己的感受，忽略對方','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>14,'TRUST_BASED'=>12]],
                ['key'=>'d','label'=>'突然全盤開放，失去神秘感','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>16,'PRESENCE'=>10]],
            ]],
            ['body'=>'你在群體中沉默時，別人通常覺得？',
             'options'=>[
                ['key'=>'a','label'=>'他一定在想什麼大事','scores'=>['MAGNETIC_C'=>2,'MYSTERIOUS_C'=>2],'dim_scores'=>['PRESENCE'=>14,'MYSTERY_C'=>12]],
                ['key'=>'b','label'=>'他今天怎麼沒有說話','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>16,'PRESENCE'=>10]],
                ['key'=>'c','label'=>'他是不是在觀察大家有沒有需要幫忙的','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>16,'TRUST_BASED'=>10]],
                ['key'=>'d','label'=>'他在想什麼我永遠猜不透','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'你最欣賞別人身上的哪種魅力特質？',
             'options'=>[
                ['key'=>'a','label'=>'那種走進一個房間就讓人想靠近的氣場','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'用語言讓人感到被理解和啟發','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'讓每個人都感到自己被重視','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'永遠有沒被完全看見的深度','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'如果魅力是一種樂器，你的是？',
             'options'=>[
                ['key'=>'a','label'=>'鼓——充滿力量，讓人感受到節奏','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>18,'EMOTIONAL'=>8]],
                ['key'=>'b','label'=>'吉他——有故事感，讓人想聽更多','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'鋼琴——溫柔且深刻，讓人感到安慰','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'大提琴——低沉有深度，讓人沉浸其中','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
            ['body'=>'你在社群媒體上的貼文風格是？',
             'options'=>[
                ['key'=>'a','label'=>'讓人感到一種難以言說的吸引力','scores'=>['MAGNETIC_C'=>3],'dim_scores'=>['PRESENCE'=>16,'EMOTIONAL'=>10]],
                ['key'=>'b','label'=>'用字精準，每句話都有畫面感','scores'=>['VERBAL_C'=>3],'dim_scores'=>['VERBAL'=>18,'PRESENCE'=>8]],
                ['key'=>'c','label'=>'溫暖真誠，讓人感到被陪伴','scores'=>['WARM_C'=>3],'dim_scores'=>['EMOTIONAL'=>18,'TRUST_BASED'=>8]],
                ['key'=>'d','label'=>'耐人尋味，讓人想多看幾次','scores'=>['MYSTERIOUS_C'=>3],'dim_scores'=>['MYSTERY_C'=>18,'PRESENCE'=>8]],
            ]],
        ]);
    }

    // =========================================================================
    // 行為模式 (需補到 50 題，目前 21 題，補 29 題)
    // =========================================================================
    private function expandBehavior(): void
    {
        $this->addQuestions('behavior-pattern', [
            ['body'=>'你在一個沒有明確規定的環境裡，會怎麼做？',
             'options'=>[
                ['key'=>'a','label'=>'自己建立規則和框架','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'直接開始做，看哪條路走得通','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'先觀察其他人怎麼做','scores'=>['ANALYZER'=>3],'dim_scores'=>['ATTENTION'=>16,'PLANNING'=>10]],
                ['key'=>'d','label'=>'問別人的意見再決定','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你在工作中最讓人依賴的特質是？',
             'options'=>[
                ['key'=>'a','label'=>'準時、有條理，可以被信任','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>16,'ATTENTION'=>10]],
                ['key'=>'b','label'=>'動作快，遇到問題可以快速解決','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'做事細心，不輕易漏掉細節','scores'=>['DETAIL'=>3],'dim_scores'=>['ATTENTION'=>18,'PLANNING'=>8]],
                ['key'=>'d','label'=>'讓大家想合作，有凝聚力','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你如何面對一個超出預期的挑戰？',
             'options'=>[
                ['key'=>'a','label'=>'重新規劃時間表和優先順序','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'直接面對，邊做邊想辦法','scores'=>['IMPULSE'=>2,'RISK_TAKER'=>2],'dim_scores'=>['SPEED'=>14,'RISK'=>12]],
                ['key'=>'c','label'=>'分析挑戰的本質，找出關鍵因素','scores'=>['ANALYZER'=>3],'dim_scores'=>['ATTENTION'=>16,'PLANNING'=>10]],
                ['key'=>'d','label'=>'看大局，不被細節困住','scores'=>['BIG_PICTURE'=>3],'dim_scores'=>['PLANNING'=>12,'RISK'=>14]],
            ]],
            ['body'=>'你對「多工處理」的態度是？',
             'options'=>[
                ['key'=>'a','label'=>'不喜歡，我需要專注在一件事上','scores'=>['DETAIL'=>2,'PLANNER'=>2],'dim_scores'=>['ATTENTION'=>14,'PLANNING'=>12]],
                ['key'=>'b','label'=>'沒問題，我可以同時處理很多事','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'看情況，但我偏好先把一件做完','scores'=>['ANALYZER'=>3],'dim_scores'=>['PLANNING'=>14,'ATTENTION'=>12]],
                ['key'=>'d','label'=>'需要有好的系統才能多工','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
            ]],
            ['body'=>'你在討論中最常扮演的角色是？',
             'options'=>[
                ['key'=>'a','label'=>'整理思路，讓討論有方向','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>16,'ATTENTION'=>10]],
                ['key'=>'b','label'=>'提出新點子，讓討論更活躍','scores'=>['IMPULSE'=>2,'RISK_TAKER'=>2],'dim_scores'=>['SPEED'=>12,'RISK'=>14]],
                ['key'=>'c','label'=>'確保所有觀點都被考慮到','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
                ['key'=>'d','label'=>'提出批判性問題，讓邏輯更嚴謹','scores'=>['ANALYZER'=>3],'dim_scores'=>['ATTENTION'=>16,'PLANNING'=>10]],
            ]],
            ['body'=>'你最害怕在工作上出現哪種情況？',
             'options'=>[
                ['key'=>'a','label'=>'事情超出了我預先的計畫','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'被要求等待，不能馬上行動','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'被分配到我認為沒意義的工作','scores'=>['BIG_PICTURE'=>3],'dim_scores'=>['PLANNING'=>12,'RISK'=>14]],
                ['key'=>'d','label'=>'我犯了一個本可避免的小錯誤','scores'=>['DETAIL'=>3],'dim_scores'=>['ATTENTION'=>18,'PLANNING'=>8]],
            ]],
            ['body'=>'你如何處理模糊不清的指示？',
             'options'=>[
                ['key'=>'a','label'=>'先把它梳理清楚，才開始執行','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>16,'ATTENTION'=>10]],
                ['key'=>'b','label'=>'先嘗試一個方向，邊做邊澄清','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'向關鍵人確認，避免方向偏差','scores'=>['COLLABORATOR'=>2,'ANALYZER'=>2],'dim_scores'=>['COOPERATION'=>12,'PLANNING'=>14]],
                ['key'=>'d','label'=>'把模糊的部分記下來，之後問清楚','scores'=>['DETAIL'=>3],'dim_scores'=>['ATTENTION'=>18,'PLANNING'=>8]],
            ]],
            ['body'=>'你在一個需要長期堅持的項目中，最難的部分是？',
             'options'=>[
                ['key'=>'a','label'=>'保持計畫不因臨時狀況而走偏','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'在進展緩慢時維持動力','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>16,'RISK'=>10]],
                ['key'=>'c','label'=>'確保每個細節都按預期完成','scores'=>['DETAIL'=>3],'dim_scores'=>['ATTENTION'=>18,'PLANNING'=>8]],
                ['key'=>'d','label'=>'讓所有人持續朝同一方向走','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你如何學習一個全新的技能？',
             'options'=>[
                ['key'=>'a','label'=>'找一個結構化的課程，按步驟學','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'直接開始試，犯錯就修正','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'先研究原理，理解了再做','scores'=>['ANALYZER'=>3],'dim_scores'=>['ATTENTION'=>16,'PLANNING'=>10]],
                ['key'=>'d','label'=>'找個厲害的人帶我學','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你認為什麼是讓一個項目成功最重要的因素？',
             'options'=>[
                ['key'=>'a','label'=>'清晰的計畫和按時執行','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'敢於嘗試和快速迭代','scores'=>['IMPULSE'=>2,'RISK_TAKER'=>2],'dim_scores'=>['SPEED'=>14,'RISK'=>12]],
                ['key'=>'c','label'=>'對每個細節的高度掌握','scores'=>['DETAIL'=>3],'dim_scores'=>['ATTENTION'=>18,'PLANNING'=>8]],
                ['key'=>'d','label'=>'團隊的高度信任和合作','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你在評估一個方案時，最重視的是？',
             'options'=>[
                ['key'=>'a','label'=>'這個方案是否可以被完整執行','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'這個方案是否夠大膽、有突破性','scores'=>['RISK_TAKER'=>3],'dim_scores'=>['RISK'=>18,'SPEED'=>8]],
                ['key'=>'c','label'=>'這個方案的潛在問題在哪裡','scores'=>['ANALYZER'=>3],'dim_scores'=>['ATTENTION'=>16,'PLANNING'=>10]],
                ['key'=>'d','label'=>'這個方案對整體目標的影響','scores'=>['BIG_PICTURE'=>3],'dim_scores'=>['PLANNING'=>12,'RISK'=>14]],
            ]],
            ['body'=>'你在截止日前，通常是？',
             'options'=>[
                ['key'=>'a','label'=>'早早完成，留時間檢查','scores'=>['PLANNER'=>2,'DETAIL'=>2],'dim_scores'=>['PLANNING'=>14,'ATTENTION'=>12]],
                ['key'=>'b','label'=>'在最後關頭衝刺，壓力下更有效率','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'按計畫穩定推進，不急不慢','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'d','label'=>'反覆確認細節，確保沒有遺漏','scores'=>['DETAIL'=>3],'dim_scores'=>['ATTENTION'=>18,'PLANNING'=>8]],
            ]],
            ['body'=>'你對「完美主義」的態度是？',
             'options'=>[
                ['key'=>'a','label'=>'我追求完美，但也知道要取捨','scores'=>['PLANNER'=>2,'DETAIL'=>2],'dim_scores'=>['PLANNING'=>12,'ATTENTION'=>14]],
                ['key'=>'b','label'=>'完成比完美更重要','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'在我在意的事上，細節很重要','scores'=>['DETAIL'=>3],'dim_scores'=>['ATTENTION'=>18,'PLANNING'=>8]],
                ['key'=>'d','label'=>'看大方向是否對了比細節更重要','scores'=>['BIG_PICTURE'=>3],'dim_scores'=>['PLANNING'=>12,'RISK'=>14]],
            ]],
            ['body'=>'你如何決定什麼事應該優先做？',
             'options'=>[
                ['key'=>'a','label'=>'按緊急程度和重要性排序','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'先做最難的，之後就輕鬆了','scores'=>['IMPULSE'=>2,'RISK_TAKER'=>2],'dim_scores'=>['SPEED'=>12,'RISK'=>14]],
                ['key'=>'c','label'=>'根據對整體目標的影響程度','scores'=>['BIG_PICTURE'=>3],'dim_scores'=>['PLANNING'=>12,'RISK'=>14]],
                ['key'=>'d','label'=>'和團隊確認，確保大家方向一致','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你在獨立工作時，最需要的條件是？',
             'options'=>[
                ['key'=>'a','label'=>'清晰的目標和里程碑','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'足夠的自主空間，不被過多干涉','scores'=>['SOLO_PERFORMER'=>3],'dim_scores'=>['SPEED'=>14,'RISK'=>12]],
                ['key'=>'c','label'=>'完整的背景資料和相關資訊','scores'=>['ANALYZER'=>3],'dim_scores'=>['ATTENTION'=>16,'PLANNING'=>10]],
                ['key'=>'d','label'=>'知道有人可以討論和協助','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你如何讓自己在高壓下保持清醒？',
             'options'=>[
                ['key'=>'a','label'=>'回到我的計畫和清單','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'加快節奏，讓行動消耗壓力','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'退一步，看清楚整體的狀況','scores'=>['BIG_PICTURE'=>3],'dim_scores'=>['PLANNING'=>12,'RISK'=>14]],
                ['key'=>'d','label'=>'和信任的人討論，整理思路','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你對「規則」的態度是？',
             'options'=>[
                ['key'=>'a','label'=>'規則讓事情更有效率，我支持','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'規則是參考用的，重要的是結果','scores'=>['IMPULSE'=>2,'RISK_TAKER'=>2],'dim_scores'=>['SPEED'=>12,'RISK'=>14]],
                ['key'=>'c','label'=>'我會細心理解規則背後的原因','scores'=>['ANALYZER'=>3],'dim_scores'=>['ATTENTION'=>16,'PLANNING'=>10]],
                ['key'=>'d','label'=>'規則是大家一起訂的，要有共識','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你在一個失敗的項目後，第一件事是？',
             'options'=>[
                ['key'=>'a','label'=>'分析哪裡出了問題，避免再犯','scores'=>['ANALYZER'=>3],'dim_scores'=>['ATTENTION'=>16,'PLANNING'=>10]],
                ['key'=>'b','label'=>'快速重新開始，不在失敗上停留太久','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'整理教訓，更新計畫','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'d','label'=>'和團隊討論，一起找出原因','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你最享受的工作狀態是？',
             'options'=>[
                ['key'=>'a','label'=>'一切按計畫，有條不紊地推進','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'快速行動，看到即時的成果','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'深度專注，把一件事做到極致','scores'=>['DETAIL'=>2,'SOLO_PERFORMER'=>2],'dim_scores'=>['ATTENTION'=>14,'PLANNING'=>12]],
                ['key'=>'d','label'=>'和好的夥伴一起創造出某件事','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你如何衡量自己的工作成效？',
             'options'=>[
                ['key'=>'a','label'=>'看是否達到預定的目標和時間表','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'看完成了多少事，進展速度','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'看細節是否都到位，品質是否達標','scores'=>['DETAIL'=>3],'dim_scores'=>['ATTENTION'=>18,'PLANNING'=>8]],
                ['key'=>'d','label'=>'看整體方向是否符合更大的目標','scores'=>['BIG_PICTURE'=>3],'dim_scores'=>['PLANNING'=>12,'RISK'=>14]],
            ]],
            ['body'=>'你認為好的領導者最重要的特質是？',
             'options'=>[
                ['key'=>'a','label'=>'有清晰的計畫和執行力','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'果斷行動，在不確定中帶領大家','scores'=>['RISK_TAKER'=>3],'dim_scores'=>['RISK'=>18,'SPEED'=>8]],
                ['key'=>'c','label'=>'細心照顧每個人的狀態和需求','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
                ['key'=>'d','label'=>'看到別人看不到的大格局','scores'=>['BIG_PICTURE'=>3],'dim_scores'=>['PLANNING'=>12,'RISK'=>14]],
            ]],
            ['body'=>'你在什麼情況下最能感到工作的滿足感？',
             'options'=>[
                ['key'=>'a','label'=>'複雜的事被我整理得井井有條','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'在高壓下完成了別人認為很難的事','scores'=>['RISK_TAKER'=>2,'IMPULSE'=>2],'dim_scores'=>['SPEED'=>14,'RISK'=>12]],
                ['key'=>'c','label'=>'每個細節都如我預期地完美執行','scores'=>['DETAIL'=>3],'dim_scores'=>['ATTENTION'=>18,'PLANNING'=>8]],
                ['key'=>'d','label'=>'我的貢獻讓整個團隊更好','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你在合作上最大的挑戰是？',
             'options'=>[
                ['key'=>'a','label'=>'別人不按計畫行事','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>16,'ATTENTION'=>10]],
                ['key'=>'b','label'=>'合作讓進度變慢','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'有人不在意細節和品質','scores'=>['DETAIL'=>3],'dim_scores'=>['ATTENTION'=>18,'PLANNING'=>8]],
                ['key'=>'d','label'=>'有人只在意自己，不考慮整體','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你如何對待工作上的模糊地帶？',
             'options'=>[
                ['key'=>'a','label'=>'盡量把模糊的事定義清楚','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'接受模糊，在不確定中前進','scores'=>['IMPULSE'=>2,'RISK_TAKER'=>2],'dim_scores'=>['SPEED'=>12,'RISK'=>14]],
                ['key'=>'c','label'=>'分析模糊的原因，找到可以確定的部分','scores'=>['ANALYZER'=>3],'dim_scores'=>['ATTENTION'=>16,'PLANNING'=>10]],
                ['key'=>'d','label'=>'和相關人討論，達成共識','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你在一個全新的環境裡，最先適應的方式是？',
             'options'=>[
                ['key'=>'a','label'=>'建立自己的系統和規律','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'馬上嘗試，邊做邊學','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'仔細觀察環境和人，理解規則','scores'=>['ANALYZER'=>3],'dim_scores'=>['ATTENTION'=>16,'PLANNING'=>10]],
                ['key'=>'d','label'=>'先找到關鍵人，建立關係','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你最欣賞哪種工作夥伴？',
             'options'=>[
                ['key'=>'a','label'=>'可靠、守時、按計畫執行','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'主動積極，遇到問題直接面對','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'細心負責，不放過任何細節','scores'=>['DETAIL'=>3],'dim_scores'=>['ATTENTION'=>18,'PLANNING'=>8]],
                ['key'=>'d','label'=>'溝通能力強，讓整個團隊更有凝聚力','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
            ['body'=>'你在工作上的座右銘是？',
             'options'=>[
                ['key'=>'a','label'=>'凡事都要有計畫，準備好了再行動','scores'=>['PLANNER'=>3],'dim_scores'=>['PLANNING'=>18,'ATTENTION'=>8]],
                ['key'=>'b','label'=>'先做了再說，調整比猶豫快','scores'=>['IMPULSE'=>3],'dim_scores'=>['SPEED'=>18,'RISK'=>8]],
                ['key'=>'c','label'=>'細節是魔鬼，也是天使','scores'=>['DETAIL'=>3],'dim_scores'=>['ATTENTION'=>18,'PLANNING'=>8]],
                ['key'=>'d','label'=>'一個人走得快，一群人走得遠','scores'=>['COLLABORATOR'=>3],'dim_scores'=>['COOPERATION'=>18,'SPEED'=>8]],
            ]],
        ]);
    }

    // =========================================================================
    // 第一印象類型 (需補到 50 題，目前 14 題，補 36 題)
    // =========================================================================
    private function expandFirstImpression(): void
    {
        $this->addQuestions('first-impression', [
            ['body'=>'你認為人們第一眼看到你時，最先判斷的是什麼？',
             'options'=>[
                ['key'=>'a','label'=>'你是否有自信和主導力','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'你是否友善和容易接近','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'你是否有深度和特別之處','scores'=>['ANALYTICAL_FI'=>2,'MYSTERIOUS_FI'=>2],'dim_scores'=>['ANALYSIS'=>12,'MYSTERY'=>14]],
                ['key'=>'d','label'=>'你的整體形象是否符合場合','scores'=>['VISUAL_FI'=>3],'dim_scores'=>['OBSERVATION'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'第一次見面之後，你最希望對方對你有什麼感覺？',
             'options'=>[
                ['key'=>'a','label'=>'欽佩，覺得我很厲害','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'溫暖，覺得我很好相處','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'好奇，想要更了解我','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'有收穫，覺得和我說話很有意義','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你在一個重要的初次見面前，最會準備什麼？',
             'options'=>[
                ['key'=>'a','label'=>'練習自我介紹，確保表達自信','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'想一些可以打開話題的問題','scores'=>['WARM_FI'=>2,'SOCIAL_FI'=>2],'dim_scores'=>['WARMTH'=>12,'OBSERVATION'=>14]],
                ['key'=>'c','label'=>'了解對方的背景，找共同話題','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'讓自己穿得好看，外在形象到位','scores'=>['VISUAL_FI'=>3],'dim_scores'=>['OBSERVATION'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你如何在短時間內讓人記住你？',
             'options'=>[
                ['key'=>'a','label'=>'用一個強烈的自我介紹','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'讓對方感到被真心對待','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'說出一個讓他們思考的問題或觀點','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>16,'CONFIDENCE'=>10]],
                ['key'=>'d','label'=>'展現一個讓人好奇的細節或特點','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你認為哪種人最容易讓人在第一次見面就喜歡？',
             'options'=>[
                ['key'=>'a','label'=>'充滿自信、有主見的人','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'溫暖真誠、讓人放鬆的人','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'聰明有趣、話題豐富的人','scores'=>['ANALYTICAL_FI'=>2,'VERBAL_FI'=>2],'dim_scores'=>['ANALYSIS'=>14,'CONFIDENCE'=>12]],
                ['key'=>'d','label'=>'有風格、形象鮮明的人','scores'=>['VISUAL_FI'=>3],'dim_scores'=>['OBSERVATION'=>16,'CONFIDENCE'=>10]],
            ]],
            ['body'=>'你在第一次見面時，對方的哪個細節會讓你印象加分？',
             'options'=>[
                ['key'=>'a','label'=>'他走進來時的氣場和姿態','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'他的眼神，有沒有真的在看我','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>16,'OBSERVATION'=>10]],
                ['key'=>'c','label'=>'他說話的邏輯和深度','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'他的整體造型是否有品味','scores'=>['VISUAL_FI'=>3],'dim_scores'=>['OBSERVATION'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你覺得自己在哪種場合給人的第一印象最好？',
             'options'=>[
                ['key'=>'a','label'=>'正式的場合，有機會展現能力','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'輕鬆的聚會，可以自然互動','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'需要有深度討論的場合','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'需要創意和獨特性的場合','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>16,'OBSERVATION'=>10]],
            ]],
            ['body'=>'你認為第一印象最難改變的元素是？',
             'options'=>[
                ['key'=>'a','label'=>'一個人的氣場和自信','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'一個人給人的溫度感','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'一個人第一次說話的內容','scores'=>['VERBAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>16,'CONFIDENCE'=>10]],
                ['key'=>'d','label'=>'一個人整體的外觀形象','scores'=>['VISUAL_FI'=>3],'dim_scores'=>['OBSERVATION'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你見到某人 5 分鐘後，你通常已經判斷了什麼？',
             'options'=>[
                ['key'=>'a','label'=>'他是否有足夠的自信和能力','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'他是否真誠，值不值得信任','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>16,'OBSERVATION'=>10]],
                ['key'=>'c','label'=>'他的智識水平和談吐','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'他是否有那種難以言說的吸引力','scores'=>['INTUITIVE_FI'=>3],'dim_scores'=>['INTUITION'=>18,'WARMTH'=>8]],
            ]],
            ['body'=>'你最不喜歡在初次見面時遇到哪種人？',
             'options'=>[
                ['key'=>'a','label'=>'過於強勢，讓我感到被壓迫','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>14,'WARMTH'=>12]],
                ['key'=>'b','label'=>'冷漠疏離，讓我不知如何靠近','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>14,'OBSERVATION'=>12]],
                ['key'=>'c','label'=>'膚淺無聊，沒有任何深度','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>14,'CONFIDENCE'=>12]],
                ['key'=>'d','label'=>'毫無記憶點，像誰都可以換一個','scores'=>['VISUAL_FI'=>2,'MYSTERIOUS_FI'=>2],'dim_scores'=>['OBSERVATION'=>12,'MYSTERY'=>14]],
            ]],
            ['body'=>'你在第一次見面後，對方給你留下了好印象，主要是因為？',
             'options'=>[
                ['key'=>'a','label'=>'他展現了一種很有力量的自信','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'他讓我感覺到真誠的關心','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'他說的話有深度，讓我受益','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'他有種讓我想繼續了解的神秘','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你認為初次見面中，哪種行為最加分？',
             'options'=>[
                ['key'=>'a','label'=>'主動說話，展現主導力','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'用心傾聽，讓對方感到被重視','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'說出有洞察力的觀點','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'讓自己的穿著和形象完美','scores'=>['VISUAL_FI'=>3],'dim_scores'=>['OBSERVATION'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你認為第一印象裡最難被忘記的是？',
             'options'=>[
                ['key'=>'a','label'=>'一個讓人感到震撼的氣場','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'一種真誠的、讓人感到溫暖的表情','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'一句讓人深思的話','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>16,'CONFIDENCE'=>10]],
                ['key'=>'d','label'=>'一種獨特的、無法複製的風格','scores'=>['MYSTERIOUS_FI'=>2,'VISUAL_FI'=>2],'dim_scores'=>['MYSTERY'=>14,'OBSERVATION'=>12]],
            ]],
            ['body'=>'你對「第一印象不代表一切」這句話的看法是？',
             'options'=>[
                ['key'=>'a','label'=>'我不認同，第一印象非常關鍵','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>16,'WARMTH'=>10]],
                ['key'=>'b','label'=>'對，有些人越相處越好','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'對，真正的深度需要時間才能顯現','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'對，有些人天生就不擅長第一印象','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>16,'OBSERVATION'=>10]],
            ]],
            ['body'=>'你認為自己的第一印象的弱點是什麼？',
             'options'=>[
                ['key'=>'a','label'=>'有時太強勢，讓人感到壓力','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>14,'WARMTH'=>12]],
                ['key'=>'b','label'=>'有時太熱情，顯得不夠冷靜','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>14,'OBSERVATION'=>12]],
                ['key'=>'c','label'=>'有時太嚴肅，讓人覺得難以接近','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>14,'CONFIDENCE'=>12]],
                ['key'=>'d','label'=>'有時太安靜，讓人不知道我在想什麼','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>14,'OBSERVATION'=>12]],
            ]],
            ['body'=>'你在初次見面後，通常自我感覺如何？',
             'options'=>[
                ['key'=>'a','label'=>'滿意，我表現了我想要展現的','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'輕鬆，只要對方感覺舒服就好','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'反思，想想有沒有說錯什麼','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>16,'CONFIDENCE'=>10]],
                ['key'=>'d','label'=>'難說，我不確定對方怎麼看我','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>14,'OBSERVATION'=>12]],
            ]],
            ['body'=>'你最希望陌生人對你的第一印象是？',
             'options'=>[
                ['key'=>'a','label'=>'「這個人很有存在感和個人魅力」','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'「這個人讓我感到很舒服」','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'「這個人說話很有深度，值得深交」','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'「這個人很有個性，讓我好奇」','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你認為哪種第一印象最難被打破？',
             'options'=>[
                ['key'=>'a','label'=>'一個人展現的自信和能力感','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'一個人散發的溫暖和安全感','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'一個人初次表達的智識和深度','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'一個人在初見時呈現的整體形象','scores'=>['VISUAL_FI'=>3],'dim_scores'=>['OBSERVATION'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你覺得哪種場合最能展現你最真實的吸引力？',
             'options'=>[
                ['key'=>'a','label'=>'在需要展現能力和主導力的場合','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'在需要建立連結和情感交流的場合','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'在可以展現思想深度的討論場合','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'在可以自由表達個人風格的場合','scores'=>['VISUAL_FI'=>2,'MYSTERIOUS_FI'=>2],'dim_scores'=>['MYSTERY'=>14,'OBSERVATION'=>12]],
            ]],
            ['body'=>'你最擔心在初次見面時給人哪種印象？',
             'options'=>[
                ['key'=>'a','label'=>'顯得不夠自信或軟弱','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>16,'WARMTH'=>10]],
                ['key'=>'b','label'=>'顯得冷漠或不好接近','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>16,'OBSERVATION'=>10]],
                ['key'=>'c','label'=>'顯得無聊或沒有深度','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>16,'CONFIDENCE'=>10]],
                ['key'=>'d','label'=>'顯得普通或毫無記憶點','scores'=>['MYSTERIOUS_FI'=>2,'VISUAL_FI'=>2],'dim_scores'=>['MYSTERY'=>14,'OBSERVATION'=>12]],
            ]],
            ['body'=>'你在第一次見面時，如何讓對話繼續下去？',
             'options'=>[
                ['key'=>'a','label'=>'主動帶領話題的方向','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'問對方感興趣的問題','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>16,'OBSERVATION'=>10]],
                ['key'=>'c','label'=>'提出一個有深度的觀點引發討論','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'讓對話有一種讓人想繼續的神秘感','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>16,'OBSERVATION'=>10]],
            ]],
            ['body'=>'你認為第一印象中最能看出一個人真實性格的細節是？',
             'options'=>[
                ['key'=>'a','label'=>'他是否主動、還是等待別人來找他','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'他是否真的在聽你說話','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'他說的第一個問題或觀點','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'他在不說話時的表情和狀態','scores'=>['INTUITIVE_FI'=>3],'dim_scores'=>['INTUITION'=>16,'WARMTH'=>10]],
            ]],
            ['body'=>'你在初次見面後，最想立刻做的事是？',
             'options'=>[
                ['key'=>'a','label'=>'確認對方對我的印象是正面的','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>16,'WARMTH'=>10]],
                ['key'=>'b','label'=>'傳一個訊息讓對方知道我很高興認識他','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'回想這段對話有什麼有趣的觀點','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>16,'CONFIDENCE'=>10]],
                ['key'=>'d','label'=>'什麼都不做，讓對方先想到我','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你如何在一個充滿強大個性的場合中脫穎而出？',
             'options'=>[
                ['key'=>'a','label'=>'展現我的自信和不被影響的主見','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'成為那個讓每個人感到被照顧的人','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'說出最有洞見的那句話','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'用我的獨特性讓人記住','scores'=>['MYSTERIOUS_FI'=>2,'VISUAL_FI'=>2],'dim_scores'=>['MYSTERY'=>14,'OBSERVATION'=>12]],
            ]],
            ['body'=>'你如何判斷對方第一次見面時是否喜歡你？',
             'options'=>[
                ['key'=>'a','label'=>'看他有沒有給我足夠的尊重和關注','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'感受他的眼神和肢體語言','scores'=>['WARM_FI'=>2,'INTUITIVE_FI'=>2],'dim_scores'=>['WARMTH'=>12,'INTUITION'=>14]],
                ['key'=>'c','label'=>'看他對我的話是否有真正的回應','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'我很難判斷，這對我來說不重要','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>14,'OBSERVATION'=>12]],
            ]],
            ['body'=>'你最希望在初次見面結束時，對方心裡想的是？',
             'options'=>[
                ['key'=>'a','label'=>'「這個人很有能力，很值得認識」','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'「這個人讓我感覺很好，希望再見到他」','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'「這個人很有思想，我學到了東西」','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'「這個人很有趣，我想更了解他」','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你覺得自己最有魅力的初次見面狀態是？',
             'options'=>[
                ['key'=>'a','label'=>'知道自己要什麼，說話有方向','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'完全放鬆，讓自然的自己出現','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'思路清晰，能說出有見解的話','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'有點神秘，讓人想繼續探索','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你認為初次見面中最能建立連結的方式是？',
             'options'=>[
                ['key'=>'a','label'=>'展現你真正的能力和價值','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'找到共同點，讓彼此感到親近','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'提出一個引發共鳴的深刻觀點','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'讓對方想要更了解你','scores'=>['MYSTERIOUS_FI'=>3],'dim_scores'=>['MYSTERY'=>18,'CONFIDENCE'=>8]],
            ]],
            ['body'=>'你覺得第一印象最終由什麼決定？',
             'options'=>[
                ['key'=>'a','label'=>'你展現的主導力和自信程度','scores'=>['CONFIDENT_FI'=>3],'dim_scores'=>['CONFIDENCE'=>18,'WARMTH'=>8]],
                ['key'=>'b','label'=>'對方感受到的真誠程度','scores'=>['WARM_FI'=>3],'dim_scores'=>['WARMTH'=>18,'OBSERVATION'=>8]],
                ['key'=>'c','label'=>'你說話的深度和智識水平','scores'=>['ANALYTICAL_FI'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONFIDENCE'=>8]],
                ['key'=>'d','label'=>'你整體呈現的形象和風格','scores'=>['VISUAL_FI'=>3],'dim_scores'=>['OBSERVATION'=>18,'CONFIDENCE'=>8]],
            ]],
        ]);
    }

    // =========================================================================
    // 人生方向 (需補到 50 題，目前 12 題，補 38 題)
    // =========================================================================
    private function expandLifeDirection(): void
    {
        $this->addQuestions('life-direction', [
            ['body'=>'你在人生的哪個時刻感到最有活力？',
             'options'=>[
                ['key'=>'a','label'=>'突破了一個以前做不到的極限','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'做了一件對他人有真實幫助的事','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'做了一個完全由自己決定的選擇','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'和重要的人有了真正深刻的連結','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'如果你能選擇一個遺產留給後人，你希望它是？',
             'options'=>[
                ['key'=>'a','label'=>'一個讓人景仰的成就','scores'=>['ACHIEVER'=>2,'LEGACY_BUILDER'=>2],'dim_scores'=>['ACHIEVEMENT'=>14,'MEANING'=>12]],
                ['key'=>'b','label'=>'一個讓世界更好的改變','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'一個讓人更自由、更勇敢的故事','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'一段讓人永遠感念的深厚關係','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你覺得什麼讓一個人的人生是「值得的」？',
             'options'=>[
                ['key'=>'a','label'=>'他實現了他設定的目標','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'他對身邊的人和社會有正面的影響','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'他真正按照自己的方式活著','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'他擁有了真實的愛和深厚的關係','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你在面對人生的岔路時，你的決策標準是什麼？',
             'options'=>[
                ['key'=>'a','label'=>'哪條路能帶我到更高的成就','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'哪條路讓我的存在更有意義','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'哪條路讓我保有最多自由','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'哪條路讓我和重要的人走在一起','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你認為人生中哪種「損失」最難接受？',
             'options'=>[
                ['key'=>'a','label'=>'未能達到我設定的目標','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>16,'MEANING'=>10]],
                ['key'=>'b','label'=>'感覺自己的存在沒有意義','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'失去了選擇和自由的空間','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'失去了一段深刻的關係','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你認為什麼是讓一個人持續前進的最深動力？',
             'options'=>[
                ['key'=>'a','label'=>'對成就和突破的渴望','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'對貢獻和影響力的渴望','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'對自由和探索的渴望','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'對連結和愛的渴望','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你對「安全感」的看法是？',
             'options'=>[
                ['key'=>'a','label'=>'安全感來自於持續的成長和成就','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>16,'MEANING'=>10]],
                ['key'=>'b','label'=>'安全感來自於相信自己在做有意義的事','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'安全感來自於知道自己有選擇的自由','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'安全感來自於重要的人在身邊','scores'=>['CONNECTOR'=>2,'SECURITY_SEEKER'=>2],'dim_scores'=>['CONNECTION'=>14,'SECURITY'=>12]],
            ]],
            ['body'=>'你如何判斷現在的生活是否符合你的核心價值？',
             'options'=>[
                ['key'=>'a','label'=>'看我是否在進步和達成目標','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'看我的行動是否對更大的事有貢獻','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'看我是否有足夠的自主空間','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'看我和重要的人的關係是否深刻','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你覺得什麼讓一個人的存在「有重量」？',
             'options'=>[
                ['key'=>'a','label'=>'他在自己的領域做出了不平凡的成就','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'他的存在讓周圍的人的生命更好','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'他走出了一條屬於自己的路','scores'=>['FREE_SPIRIT'=>2,'EXPLORER'=>2],'dim_scores'=>['FREEDOM'=>14,'MEANING'=>12]],
                ['key'=>'d','label'=>'他建立了讓人永難忘懷的深刻關係','scores'=>['CONNECTOR'=>2,'LEGACY_BUILDER'=>2],'dim_scores'=>['CONNECTION'=>14,'MEANING'=>12]],
            ]],
            ['body'=>'在你最後的日子裡，你希望身邊最多的是？',
             'options'=>[
                ['key'=>'a','label'=>'你一生中達成的成就的紀錄','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'曾被你幫助過的人的感謝','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'你探索過的世界和故事','scores'=>['FREE_SPIRIT'=>2,'EXPLORER'=>2],'dim_scores'=>['FREEDOM'=>14,'MEANING'=>12]],
                ['key'=>'d','label'=>'你最愛的人的陪伴','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你對「平凡的生活」有什麼感受？',
             'options'=>[
                ['key'=>'a','label'=>'平凡代表我沒有充分發揮潛力','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'平凡沒問題，只要生命有意義','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'平凡讓我感到窒息，我需要更多','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'平凡的生活如果有深刻的關係也是幸福','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你如何定義「真正的勇氣」？',
             'options'=>[
                ['key'=>'a','label'=>'面對高難度的挑戰，不退縮','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'為了更大的意義，犧牲個人利益','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'選擇一條不確定的路，只因為感覺對','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'在關係中保持真實，不戴面具','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>16,'SECURITY'=>10]],
            ]],
            ['body'=>'你如何看待「改變」這件事？',
             'options'=>[
                ['key'=>'a','label'=>'改變是成長的必要條件，我歡迎它','scores'=>['ACHIEVER'=>2,'EXPLORER'=>2],'dim_scores'=>['ACHIEVEMENT'=>12,'FREEDOM'=>14]],
                ['key'=>'b','label'=>'改變需要有意義，不是為了改變而改變','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'改變是生命的樂趣，我享受未知','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'改變要在不傷害重要關係的前提下','scores'=>['CONNECTOR'=>2,'SECURITY_SEEKER'=>2],'dim_scores'=>['CONNECTION'=>12,'SECURITY'=>14]],
            ]],
            ['body'=>'你在做一個重大決定時，最後你問自己的問題是什麼？',
             'options'=>[
                ['key'=>'a','label'=>'這個決定會讓我更接近我的目標嗎？','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'這個決定符合我的核心價值嗎？','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'這個決定是真的我想要的，還是別人期望的？','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'這個決定對我在乎的人有什麼影響？','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你如何定義「人生中的成功」？',
             'options'=>[
                ['key'=>'a','label'=>'達到我設定的具體目標','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'讓自己的存在有正面的影響','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'過上完全由自己選擇的生活','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'擁有真正深刻的愛和連結','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你覺得「浪費了一天」是什麼感覺？',
             'options'=>[
                ['key'=>'a','label'=>'今天沒有往前進展，感到焦慮','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'今天做的事沒有意義或貢獻','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'今天被事情困住，沒有自由的空間','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'今天和重要的人沒有真正的連結','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你認為你最需要在人生中「保護」的是什麼？',
             'options'=>[
                ['key'=>'a','label'=>'我追求成就的空間和動力','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'我對自己做有意義的事的信念','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'我的自由和自主選擇的權利','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'我和重要的人的深刻關係','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你認為什麼是「不枉此生」的感覺？',
             'options'=>[
                ['key'=>'a','label'=>'我在自己的領域達到了值得驕傲的成就','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>18,'MEANING'=>8]],
                ['key'=>'b','label'=>'我知道自己的存在讓某些人的生命更好','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'我真正按照自己的方式走完這段路','scores'=>['FREE_SPIRIT'=>3],'dim_scores'=>['FREEDOM'=>18,'MEANING'=>8]],
                ['key'=>'d','label'=>'我深深愛過，也被深深愛過','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'你如何面對「人生沒有意義」這個問題？',
             'options'=>[
                ['key'=>'a','label'=>'通過創造成就來創造意義','scores'=>['ACHIEVER'=>3],'dim_scores'=>['ACHIEVEMENT'=>16,'MEANING'=>10]],
                ['key'=>'b','label'=>'意義來自你選擇賦予什麼重要性','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'去探索，直到找到讓你感到活著的事','scores'=>['FREE_SPIRIT'=>2,'EXPLORER'=>2],'dim_scores'=>['FREEDOM'=>14,'MEANING'=>12]],
                ['key'=>'d','label'=>'意義在關係裡，在你愛的人眼中','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
            ]],
            ['body'=>'如果今天是你人生的最後一天，你最遺憾沒有做的是？',
             'options'=>[
                ['key'=>'a','label'=>'那件我一直想做但沒勇氣嘗試的事','scores'=>['ACHIEVER'=>2,'FREE_SPIRIT'=>2],'dim_scores'=>['ACHIEVEMENT'=>12,'FREEDOM'=>14]],
                ['key'=>'b','label'=>'那個讓世界更好一點的計畫','scores'=>['MEANING_SEEKER'=>3],'dim_scores'=>['MEANING'=>18,'CONNECTION'=>8]],
                ['key'=>'c','label'=>'那些我一直想說但沒說出口的話','scores'=>['CONNECTOR'=>3],'dim_scores'=>['CONNECTION'=>18,'SECURITY'=>8]],
                ['key'=>'d','label'=>'那些我一直想去但沒去的地方','scores'=>['FREE_SPIRIT'=>2,'EXPLORER'=>2],'dim_scores'=>['FREEDOM'=>14,'MEANING'=>12]],
            ]],
        ]);
    }

    // =========================================================================
    // 情緒壓力管理風格 (需補到 50 題，目前 11 題，補 39 題)
    // =========================================================================
    private function expandEmotionalStress(): void
    {
        $this->addQuestions('emotional-stress', [
            ['body'=>'當你感到非常憤怒時，你最常做的是？',
             'options'=>[
                ['key'=>'a','label'=>'深呼吸，讓自己冷靜下來再處理','scores'=>['SUPPRESSOR'=>2,'RESILIENT'=>2],'dim_scores'=>['CONTROL'=>14,'RESILIENCE'=>12]],
                ['key'=>'b','label'=>'說出來，讓對方知道我的感受','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'去運動或做體力活動消耗能量','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'先迴避，讓自己冷靜後再面對','scores'=>['AVOIDER'=>3],'dim_scores'=>['AVOIDANCE'=>16,'CONTROL'=>10]],
            ]],
            ['body'=>'你在什麼情況下最難控制情緒？',
             'options'=>[
                ['key'=>'a','label'=>'感到不被尊重或被忽視','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>16,'DEPTH'=>10]],
                ['key'=>'b','label'=>'長期積累了很多沒說出口的情緒','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>14,'DEPTH'=>12]],
                ['key'=>'c','label'=>'事情不按我預期的發展','scores'=>['ANALYZER_E'=>2,'SUPPRESSOR'=>2],'dim_scores'=>['ANALYSIS'=>12,'CONTROL'=>14]],
                ['key'=>'d','label'=>'被迫面對一個我一直在逃避的事','scores'=>['AVOIDER'=>3],'dim_scores'=>['AVOIDANCE'=>16,'CONTROL'=>10]],
            ]],
            ['body'=>'你如何讓自己在一個困難的情境中保持穩定？',
             'options'=>[
                ['key'=>'a','label'=>'把情緒藏起來，讓自己看起來穩定','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>18,'DEPTH'=>8]],
                ['key'=>'b','label'=>'把感受說出來，讓情緒流動','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'關注當下的呼吸和身體感受','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'分析情況，把情緒和思考分開','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'當你看到別人在哭泣，你的第一反應是？',
             'options'=>[
                ['key'=>'a','label'=>'感到有點不知所措，不知道怎麼反應','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>16,'DEPTH'=>10]],
                ['key'=>'b','label'=>'立刻想安慰他們，問他們怎麼了','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>16,'DEPTH'=>10]],
                ['key'=>'c','label'=>'想理解背後的原因','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'給他們空間，讓他們先冷靜','scores'=>['AVOIDER'=>2,'GROUNDED'=>2],'dim_scores'=>['AVOIDANCE'=>12,'GROUNDING'=>14]],
            ]],
            ['body'=>'你在關係中，面對衝突的方式通常是？',
             'options'=>[
                ['key'=>'a','label'=>'先忍著，等對方冷靜後再說','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>16,'DEPTH'=>10]],
                ['key'=>'b','label'=>'立刻把我的感受表達清楚','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'分析誰的邏輯是對的','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'暫時離開現場，讓雙方冷靜','scores'=>['AVOIDER'=>3],'dim_scores'=>['AVOIDANCE'=>16,'CONTROL'=>10]],
            ]],
            ['body'=>'你最希望別人如何支持你度過困難時期？',
             'options'=>[
                ['key'=>'a','label'=>'不要問太多，讓我自己處理','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>18,'DEPTH'=>8]],
                ['key'=>'b','label'=>'陪我說話，讓我把感受說出來','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'幫我分析問題，找出解決方法','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'陪我做一些讓身體感到舒服的事','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你如何應對長期的慢性壓力？',
             'options'=>[
                ['key'=>'a','label'=>'繼續做事，讓自己保持忙碌','scores'=>['SUPPRESSOR'=>2,'AVOIDER'=>2],'dim_scores'=>['CONTROL'=>12,'AVOIDANCE'=>14]],
                ['key'=>'b','label'=>'找人傾訴，讓壓力有出口','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'找出壓力來源，系統性地解決','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'定期用運動或冥想重置身心','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你最難向別人表達的情緒是？',
             'options'=>[
                ['key'=>'a','label'=>'所有的情緒，我習慣一個人消化','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>18,'DEPTH'=>8]],
                ['key'=>'b','label'=>'恐懼，說出來感覺很脆弱','scores'=>['SUPPRESSOR'=>2,'AVOIDER'=>2],'dim_scores'=>['CONTROL'=>12,'AVOIDANCE'=>14]],
                ['key'=>'c','label'=>'感性的情緒，我更習慣理性表達','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'其實我不難表達，我很快就說出來','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
            ]],
            ['body'=>'你對「眼淚」這件事的態度是？',
             'options'=>[
                ['key'=>'a','label'=>'盡量不哭，感覺哭是軟弱的表現','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>18,'DEPTH'=>8]],
                ['key'=>'b','label'=>'哭是釋放，哭完反而感覺好多了','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'哭有時候是對的反應，但我喜歡理解它','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'眼淚來的時候，我會去外面走走','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>16,'CONTROL'=>10]],
            ]],
            ['body'=>'你在情緒低落時，最不想做的事是？',
             'options'=>[
                ['key'=>'a','label'=>'讓別人看到我的低落狀態','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>18,'DEPTH'=>8]],
                ['key'=>'b','label'=>'一個人待著，沒有出口','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>16,'DEPTH'=>10]],
                ['key'=>'c','label'=>'停止思考，讓情緒漫無目的地流動','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>16,'CONTROL'=>10]],
                ['key'=>'d','label'=>'直接面對讓我低落的那件事','scores'=>['AVOIDER'=>3],'dim_scores'=>['AVOIDANCE'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你如何知道自己的情緒已經到了臨界點？',
             'options'=>[
                ['key'=>'a','label'=>'突然對一件小事過度反應','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>16,'DEPTH'=>10]],
                ['key'=>'b','label'=>'說話開始變得不加過濾','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>16,'DEPTH'=>10]],
                ['key'=>'c','label'=>'大腦開始無法正常思考','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>16,'CONTROL'=>10]],
                ['key'=>'d','label'=>'身體開始出現緊繃或疼痛的感覺','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>16,'CONTROL'=>10]],
            ]],
            ['body'=>'你在一個很開心的時刻，你怎麼表達你的快樂？',
             'options'=>[
                ['key'=>'a','label'=>'微笑，但不一定外顯','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>16,'DEPTH'=>10]],
                ['key'=>'b','label'=>'馬上找人分享，讓快樂加倍','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'安靜地回味，感謝這個時刻','scores'=>['ANALYZER_E'=>2,'GROUNDED'=>2],'dim_scores'=>['ANALYSIS'=>12,'GROUNDING'=>14]],
                ['key'=>'d','label'=>'用行動慶祝，讓身體感受快樂','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你如何讓自己在一段時間後走出悲傷？',
             'options'=>[
                ['key'=>'a','label'=>'讓時間過去，讓自己自然復原','scores'=>['RESILIENT'=>3],'dim_scores'=>['RESILIENCE'=>18,'CONTROL'=>8]],
                ['key'=>'b','label'=>'徹底感受悲傷，直到它自然消退','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'分析悲傷，理解了就能放下','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'讓自己去做一件讓身體感到好的事','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你認為情緒管理最重要的能力是？',
             'options'=>[
                ['key'=>'a','label'=>'不讓情緒影響行為和判斷','scores'=>['SUPPRESSOR'=>2,'RESILIENT'=>2],'dim_scores'=>['CONTROL'=>14,'RESILIENCE'=>12]],
                ['key'=>'b','label'=>'讓情緒有適當的出口，不積累','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'了解情緒的訊號，從中學習','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'快速調節，不讓自己沉浸太久','scores'=>['RESILIENT'=>3],'dim_scores'=>['RESILIENCE'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你最擅長的情緒管理技巧是？',
             'options'=>[
                ['key'=>'a','label'=>'在不好的情緒出現時，繼續正常運作','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>18,'DEPTH'=>8]],
                ['key'=>'b','label'=>'及時說出感受，讓自己輕鬆','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'用分析來理解情緒背後的原因','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'用身體活動重置情緒狀態','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你在一個高壓的會議或討論中，你的情緒狀態通常是？',
             'options'=>[
                ['key'=>'a','label'=>'表面平靜，但內部有很多情緒','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>18,'DEPTH'=>8]],
                ['key'=>'b','label'=>'直接表達我的看法和感受','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>16,'DEPTH'=>10]],
                ['key'=>'c','label'=>'用邏輯和分析保持清醒','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'注意呼吸，讓自己保持在當下','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你如何應對別人對你說了傷心的話？',
             'options'=>[
                ['key'=>'a','label'=>'沒說什麼，回家一個人慢慢消化','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>16,'DEPTH'=>10]],
                ['key'=>'b','label'=>'當下就表達我的感受和不滿','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'想清楚他為什麼這麼說，找出原因','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'先離開現場，讓自己平靜下來','scores'=>['AVOIDER'=>2,'GROUNDED'=>2],'dim_scores'=>['AVOIDANCE'=>12,'GROUNDING'=>14]],
            ]],
            ['body'=>'你覺得你的情緒管理方式有什麼缺點？',
             'options'=>[
                ['key'=>'a','label'=>'壓久了會在不對的時機爆發','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>14,'DEPTH'=>12]],
                ['key'=>'b','label'=>'有時說得太直接，讓對方不舒服','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>14,'DEPTH'=>12]],
                ['key'=>'c','label'=>'有時過度分析，讓情緒被理智掩蓋','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>14,'CONTROL'=>12]],
                ['key'=>'d','label'=>'有時迴避太久，問題沒有真正解決','scores'=>['AVOIDER'=>3],'dim_scores'=>['AVOIDANCE'=>14,'CONTROL'=>12]],
            ]],
            ['body'=>'當你感到焦慮時，你的身體最明顯的反應是？',
             'options'=>[
                ['key'=>'a','label'=>'肩頸緊繃，下意識夾緊','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>16,'DEPTH'=>10]],
                ['key'=>'b','label'=>'話變多，需要說出來才能放鬆','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'大腦一直轉，停不下來','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'很想動，靜不下來','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>16,'CONTROL'=>10]],
            ]],
            ['body'=>'你認為讓情緒健康最重要的習慣是？',
             'options'=>[
                ['key'=>'a','label'=>'定期讓自己有安靜獨處的空間','scores'=>['SUPPRESSOR'=>2,'RESILIENT'=>2],'dim_scores'=>['CONTROL'=>12,'RESILIENCE'=>14]],
                ['key'=>'b','label'=>'定期和信任的人傾訴','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'定期做情緒日記或自我反思','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'定期做讓身體感到好的活動','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你如何幫助一個情緒崩潰的朋友？',
             'options'=>[
                ['key'=>'a','label'=>'陪著他，但不說太多','scores'=>['SUPPRESSOR'=>2,'GROUNDED'=>2],'dim_scores'=>['CONTROL'=>10,'GROUNDING'=>16]],
                ['key'=>'b','label'=>'讓他把所有感受說出來','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'幫他分析問題的原因和解法','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'帶他去散步或做讓身體放鬆的事','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你對「情緒化」這個詞的感受是？',
             'options'=>[
                ['key'=>'a','label'=>'這是缺點，我盡量不情緒化','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>18,'DEPTH'=>8]],
                ['key'=>'b','label'=>'情緒化代表感受力強，不是壞事','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'情緒化通常源自沒理解清楚情緒','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'情緒化時，我需要讓身體動起來','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你認為「壓力」對你最大的影響是什麼？',
             'options'=>[
                ['key'=>'a','label'=>'讓我越來越沉默，把事情都放在心裡','scores'=>['SUPPRESSOR'=>3],'dim_scores'=>['CONTROL'=>18,'DEPTH'=>8]],
                ['key'=>'b','label'=>'讓我說話更直接，有時失去耐心','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>16,'DEPTH'=>10]],
                ['key'=>'c','label'=>'讓我思慮過多，腦袋停不下來','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'讓我的身體變得緊繃和疲憊','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>16,'CONTROL'=>10]],
            ]],
            ['body'=>'你相信情緒需要被「管理」還是「接受」？',
             'options'=>[
                ['key'=>'a','label'=>'管理，讓情緒不影響你的行動','scores'=>['SUPPRESSOR'=>2,'RESILIENT'=>2],'dim_scores'=>['CONTROL'=>14,'RESILIENCE'=>12]],
                ['key'=>'b','label'=>'接受，讓情緒流動才是健康的','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'先理解，才能真正接受和管理','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'回到身體，兩者都會自然發生','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你在什麼情況下最容易感到情緒穩定？',
             'options'=>[
                ['key'=>'a','label'=>'當周圍一切在我的掌控中','scores'=>['SUPPRESSOR'=>2,'RESILIENT'=>2],'dim_scores'=>['CONTROL'=>16,'RESILIENCE'=>10]],
                ['key'=>'b','label'=>'當我有機會完整地表達自己','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'當我對情況有清晰的理解','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'當我的身體感到舒服和放鬆','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>18,'CONTROL'=>8]],
            ]],
            ['body'=>'你認為哪種情緒最值得被更充分地感受？',
             'options'=>[
                ['key'=>'a','label'=>'悲傷，它讓你知道什麼是真正重要的','scores'=>['EXPRESSER'=>2,'ANALYZER_E'=>2],'dim_scores'=>['EXPRESSION'=>12,'DEPTH'=>14]],
                ['key'=>'b','label'=>'憤怒，它告訴你哪裡越過了你的界線','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>16,'DEPTH'=>10]],
                ['key'=>'c','label'=>'喜悅，讓自己完全沉浸在快樂裡','scores'=>['GROUNDED'=>3],'dim_scores'=>['GROUNDING'=>16,'CONTROL'=>10]],
                ['key'=>'d','label'=>'恐懼，它指引你走向真正重要的事','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>16,'DEPTH'=>10]],
            ]],
            ['body'=>'你認為一個情緒健康的人具備什麼特質？',
             'options'=>[
                ['key'=>'a','label'=>'不讓情緒控制他的決定和行為','scores'=>['RESILIENT'=>2,'SUPPRESSOR'=>2],'dim_scores'=>['RESILIENCE'=>14,'CONTROL'=>12]],
                ['key'=>'b','label'=>'能夠真實表達他的感受，不壓抑','scores'=>['EXPRESSER'=>3],'dim_scores'=>['EXPRESSION'=>18,'DEPTH'=>8]],
                ['key'=>'c','label'=>'對自己的情緒有清晰的認識','scores'=>['ANALYZER_E'=>3],'dim_scores'=>['ANALYSIS'=>18,'CONTROL'=>8]],
                ['key'=>'d','label'=>'能夠快速從負面情緒中恢復','scores'=>['RESILIENT'=>3],'dim_scores'=>['RESILIENCE'=>18,'CONTROL'=>8]],
            ]],
        ]);
    }
}
